version: 0.1

# buildspec.yml for use with AWS CodeBuild


phases:


  install:
    commands:
      - echo Nothing to do in the install phase...

  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...

  build:
    commands:
      - echo In the build phase!
      - mvn package
      - echo "Hello, World!" > target/hello.txt

  post_build:
    commands:
      - echo Nothing to do in the post_build phase...

artifacts:
  files:
    - target/myproject-0.0.1-SNAPSHOT.jar
    - target/hello.txt

